# Generated by Django 2.2.9 on 2020-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectLocation', '0004_auto_20200307_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contratista',
            field=models.CharField(default='EL CORI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='entidad',
            field=models.CharField(default='MUNICIPALIDAD PAUCARTAMBO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado_obra',
            field=models.CharField(choices=[('Finalizada', 'F'), ('En ejecucion', 'E'), ('Paralizada', 'P'), ('Sin ejecucion', 'SE')], default='E', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modalidad_ejecucion',
            field=models.CharField(choices=[('Por Contrata', 'OPC'), ('Por Administracion Directa', 'OAD')], default='OPC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='residente',
            field=models.CharField(default='EL RESI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sector_financiamiento',
            field=models.CharField(choices=[('Agricultura', 'AG'), ('Educacion', 'ED'), ('Energia', 'EG'), ('Salud', 'SA'), ('Transporte y Comunicaciones', 'TC'), ('Vivienda, Construccion y Saneamiento', 'VCS'), ('Otros', 'O')], default='E', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='supervisor',
            field=models.CharField(default='EL SUPER', max_length=100),
            preserve_default=False,
        ),
    ]
