# Generated by Django 2.2.9 on 2020-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectLocation', '0005_auto_20200307_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(blank=True),
        ),
    ]
