# Generated by Django 2.2.9 on 2020-03-11 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectLocation', '0006_auto_20200307_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_creacion',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='snip',
            field=models.IntegerField(default=2106234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado_obra',
            field=models.CharField(choices=[('F', 'Finalizada'), ('E', 'En ejecucion'), ('P', 'Paralizada'), ('SE', 'Sin ejecucion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad_ejecucion',
            field=models.CharField(choices=[('OPC', 'Por Contrata'), ('OAD', 'Por Administracion Directa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sector_financiamiento',
            field=models.CharField(choices=[('AG', 'Agricultura'), ('ED', 'Educacion'), ('EG', 'Energia'), ('SA', 'Salud'), ('TC', 'Transporte y Comunicaciones'), ('VCS', 'Vivienda, Construccion y Saneamiento'), ('O', 'Otros')], max_length=100),
        ),
    ]
